### ISSUE TITLE
对 w2-3 提出一种新的解法

### ISSUE THREAD

**Issue by WangNianyi2001** [sunyongjian/alg-exercise#1]
const special = arr => arr.length < 3 ? null : (f => arr.find(n => n & 1 ^ f))((232 >> (arr.slice(0, 3).reduce((r, n) => n & 1 | r << 1, 0))) & 1);

总的思想是查表，取数组头三个数的末尾组成一个三位二进制数，取`232`右面第该数位作为数组主导的奇偶性。
`n&1^f`的意思是“n 的奇偶性与数组主导的奇偶性相悖”。

**Comment by sunyongjian** [comment]
@WangNianyi2001  这个 6 了，待我学习学习。
